FROM openjdk:17-jdk-alpine3.13

WORKDIR /app

COPY target/controle-fluxo-caixa-0.0.1-SNAPSHOT.jar app.jar

# Configurações do banco de dados H2
ENV SPRING_DATASOURCE_URL=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
ENV SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.h2.Driver
ENV SPRING_DATASOURCE_USERNAME=sa
ENV SPRING_DATASOURCE_PASSWORD=''

# Configurações adicionais
ENV SPRING_PROFILES_ACTIVE=docker
ENV SPRING_MAIN_BANNER_MODE=off
ENV SPRING_DATASOURCE_INITIALIZATION_MODE=always
ENV SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.H2Dialect
ENV MANAGEMENT_SERVER_PORT=1979
ENV MANAGEMENT_ENDPOINT_INFO_ENABLED=true
ENV MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=health,info,metrics

EXPOSE 8080
EXPOSE 1979

# Executa a aplicação
ENTRYPOINT ["java", "-jar", "app.jar"]